#####################################################
# service1.yml
#
# Author: Denes Solti
#####################################################
Description: Service infrastructure. Can be deployed in any region

Parameters:
  app:
    Type: String
    Description: The application name (including prefix)
    MaxLength: '32'
  image:
    Type: String
    Description: Image to be deployed
  port:
    Type: Number
    Description: Port on which the service will be listening
    Default: 1986
  healthCheckInterval:
    Type: Number
    Description: Seconds after which a new healthcheck cycle should be triggered
    Default: 60
  maxInstances:
    Type: Number
    Description: The maximum autoscaling capacity
    Default: 2

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Fn::ImportValue: !Sub "${app}-services-cluster"
      TaskDefinition: !Ref ServiceTaskDefinition
      LoadBalancers:
        - ContainerName: !Sub "${AWS::StackName}-task"
          ContainerPort: !Ref port
          TargetGroupArn: !Ref ServiceTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ServiceSecurityGroup
          Subnets:
            - Fn::ImportValue: !Sub "${app}-vpc-private-subnet-1-id"
            - Fn::ImportValue: !Sub "${app}-vpc-private-subnet-2-id"
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      ServiceName: !Ref AWS::StackName

  ServiceAutoscalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: !Ref maxInstances
      ResourceId: !Join
        - "/"
        - - service
          - Fn::ImportValue: !Sub "${app}-services-cluster"
          - Fn::GetAtt: Service.Name
      RoleARN: !GetAtt ServiceAutoScalingRole.Arn
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ServiceScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-sp"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ServiceAutoscalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 50.0

  ServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: '/healthcheck'
      HealthCheckIntervalSeconds: !Ref healthCheckInterval
      VpcId:
        Fn::ImportValue: !Sub "${app}-vpc-id"
      TargetType: ip
      Port: !Ref port
      Protocol: HTTPS
      Matcher:
        HttpCode: 200

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref ServiceTargetGroup
      Conditions:
        - Field: path-pattern
          Values:
            - "*"
      ListenerArn:
        Fn::ImportValue: !Sub "${app}-http-listener-arn"
      Priority: 666

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Service SG
      VpcId:
        Fn::ImportValue: !Sub "${app}-vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref port
          ToPort: !Ref port
          CidrIp:
            Fn::ImportValue: !Sub "${app}-vpc-public-subnet-1-cidr-ip"  # deliberately "public"
        - IpProtocol: tcp
          FromPort: !Ref port
          ToPort: !Ref port
          CidrIp:
            Fn::ImportValue: !Sub "${app}-vpc-public-subnet-1-cidr-ip"
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"

  ServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !Ref ServiceExecutionRole
      TaskRoleArn: !Ref ServiceTaskRole
      NetworkMode: awsvpc
      Cpu: 512
      Memory: 2048
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Sub "${AWS::StackName}-task"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref ServiceLogGroup
              awslogs-stream-prefix: serviceLog
          HealthCheck:
            Command:
              - CMD-SHELL
              - !Sub "curl --fail --insecure https://localhost:${port}/healthcheck || exit 1"
            Interval: !Ref healthCheckInterval
            Retries: 2
          Environment:
            - Name: SERVICE_PORT
              Value: !Ref port
            - Name: DB_NAME
              Value:
                Fn::ImportValue: !Sub "${app}-db-name"
            - Name: DB_ENDPOINT
              Value:
                Fn::ImportValue: !Sub "${app}-db-endpoint"
            - Name: DB_SECRET_ARN
              Value:
                Fn::ImportValue: !Sub "${app}-db-secret-arn"
          Image: !Ref image
          PortMappings:
            - ContainerPort: !Ref port

  ServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'ecs/services/${AWS::StackName}-task'

  ###################
  # Roles
  ###################

  ServiceAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: allowAutoscaling
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - application-autoscaling:*
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: "*"

  ServiceExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'

  ServiceTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: allowSecretManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  Fn::ImportValue: !Sub "${app}-db-secret-arn"