#####################################################
# foundation.yml
#
# Author: Denes Solti
#####################################################
Description: Foundation infrastructure. Can be deployed in any region

Parameters:
  app:
    Type: String
    Description: The application name (including prefix)
    MaxLength: '32'

Resources:
  #####################
  # Lambda bucket
  #####################

  LambdaBucket:
    Type: AWS::S3::Bucket
    Description: Bucket containing the lambda resources
    Properties:
      BucketName: !Sub "${app}-lambda-bucket"

#####################
# Outputs
#####################

Outputs:
  LambdaBucketArn:
    Value: !Ref LambdaBucket
    Export:
      Name: !Sub "${app}-lambda-bucket-name"